apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  selector:
    app: webapp-d #Bind service to  pods named webapp-d
  ports:
  - protocol: TCP
    port: 8000 #Internal port to open
    targetPort: 8000 #Port that ingress can send messages to
  type: NodePort